### ISSUE TITLE
onViewStart NullPointerException when trying to start a Feature

### ISSUE THREAD

**Issue by jreyes** [Fuusio/Robopupu#8]
When trying to start a feature in 0.4.2 is throwing the following error 

>     @Override
>     public void onMainPresenterStarted() {
>         mFeatureManager.startFeature(mView.getMainFeatureContainer(), SplashFeature.class);
>     }

This code was working on 0.4.1 and was able to trace the error to ViewActivity.onStart() where 'presenter.onViewStart(this);' (line 135-139) is happening before the FeatureProviderContainer registers in the FeatureManager (line 143-147)

**Comment by Fuusio** [comment]
What is the error you get? It was not clear from your issue description. My sample app starts its Splash Feature in very similar way and I do not get any error.

However, it is abvious that a `NullPointerException` will occur if your code causes an invocation of method `FeatureManager#getFeatureContainer(int)` before your `FeatureContainerProvider` implementation register itself to `FeatureManager`.

So, I will anyway modify method `ViewActivity#onStart()`in a way that registration of a `FeatureContainerProvider` happens before the `ViewActivity`notifies its attached `Presenter`about` `onStart()` lifecycle event. This modification should fix your error.

Thanks for the info!

**Comment by Fuusio** [comment]
Fixed in version 0.4.3
